language: c
sudo: false # only for faster builds
compiler: 
- clang
- gcc
script:
- gcc -o gayathri gayathri.c 
 - ./gayathri.c
 - gcc -o deepi deepi.c 
 - ./deepi.c
 - gcc -o supriya supriya.c 
 - ./supriya.c
 
