language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 deepi.c -o deepi
  - ./deepi
  - gcov deepi.c
  clang -coverage -O1 gayathri.c -o gayathri
  - ./gayathri
  - gcov gayathri.c
  clang -coverage -O2 supriya.c -o supriya
  - ./supriya
  - gcov supriya.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
